name: 2p-preprocess
channels:
  - pytorch
  - numba
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - mkl
  - numpy
  - numba
  - matplotlib
  - scikit-learn
  - h5py
  - pip:
    - scipy
    - pyqt5
    - torch=2.0.1
    - natsort
    - rastermap
    - tifffile
    - scanimage-tiff-reader
    - pyqtgraph
    - importlib-metadata
    - paramiko
    - pynwb
    - sbxreader
    - suite2p